App/Models/Zlecenia.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Zlecenia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zlecenia()
        {
            this.Produkty = new HashSet<Produkty>();
        }
    
        public int ZlecenieID { get; set; }
        public string Firma { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> Termin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produkty> Produkty { get; set; }
    }
}

App/Controllers/ZleceniaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using App.Models;
using PagedList;

namespace App.Controllers
{
    [Authorize]
    public class ZleceniaController : Controller
    {
        private EntityDBEntities db = new EntityDBEntities();
        
        // GET: Zlecenia
        
        public ActionResult Index(string sortowanie, string search, string filter, int? page)
        {
            
           // var query = from z in db.Zlecenia
            //            select z;
            int pageNumber = (page ?? 1);

            ViewBag.Wyszukiwanie = search;
            ViewBag.Strona = page;
            ViewBag.SortBy = sortowanie;
            ViewBag.Firma = sortowanie == "FirmaDSC" ? "FirmaASC" : "FirmaDSC";
            ViewBag.Termin = sortowanie == null ? "TerminDSC" : "";

            if(search != null)
            {
                page = 1;
            }
            else
            {
                search = filter;
            }
            ViewBag.filter = search;

            //var query = db.Zlecenia.Include(s => s.Produkty);
            var query = from z in db.Zlecenia
                        select z;

            if (!String.IsNullOrEmpty(search))
            {

                //query.Where(s => s.Firma.Contains(search) || s.Termin.ToString().Contains(search));
                query = from z in db.Zlecenia
                        where z.Firma.Contains(search) || z.Termin.ToString().Contains(search)
                        select z;

                //return View(query.ToPagedList(pageNumber, 6));
            }

            switch (sortowanie)
            {
                case "FirmaDSC":
                    query = query.OrderByDescending(s => s.Firma);
                        break;
                case "FirmaASC":
                    query = query.OrderBy(s => s.Firma);
                    break;
                case "TerminDSC":
                    query = query.OrderByDescending(s => s.Termin);
                    break;
                default:
                    query = query.OrderBy(s => s.Termin);
                    break;
            }
            
            

            return View(query.ToPagedList(pageNumber, 6));
        }






        // GET: Zlecenia/Create
        [Authorize(Roles="Admin")]
        public ActionResult Create()
        {
            return View();
        }

        
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ZlecenieID,Firma,Termin")] Zlecenia zlecenia)
        {
            if (ModelState.IsValid)
            {
                db.Zlecenia.Add(zlecenia);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(zlecenia);
        }

        // GET: Zlecenia/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Zlecenia zlecenia = db.Zlecenia.Find(id);
            if (zlecenia == null)
            {
                return HttpNotFound();
            }
            return View(zlecenia);
        }

        // POST: Zlecenia/Edit/5
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ZlecenieID,Firma,Termin")] Zlecenia zlecenia)
        {
            if (ModelState.IsValid)
            {
                db.Entry(zlecenia).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(zlecenia);
        }

        // GET: Zlecenia/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Zlecenia zlecenia = db.Zlecenia.Find(id);
            if (zlecenia == null)
            {
                return HttpNotFound();
            }
            return View(zlecenia);
        }

        // POST: Zlecenia/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Zlecenia zlecenia = db.Zlecenia.Find(id);
            db.Zlecenia.Remove(zlecenia);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

App/Views/Zlecenia/Create.cshtml
@model App.Models.Zlecenia



<h2>Nowe zlecenie</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Zlecenia</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Firma, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Firma, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Firma, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Termin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Termin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Termin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Utwórz" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Wróć do listy", "Index")
</div>

App/Views/Zlecenia/Delete.cshtml
@model App.Models.Zlecenia

@{
    ViewBag.Title = "Delete";
}



<h3>Czy na pewno chcesz usunąć to zlecenie?</h3>
<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Firma)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Firma)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Termin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Termin)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Usuń" class="btn btn-default" /> |
            @Html.ActionLink("Wróć do listy", "Index")
        </div>
    }
</div>

App/Views/Zlecenia/Details.cshtml
@model App.Models.Zlecenia

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Zlecenia</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Firma)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Firma)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Termin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Termin)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ZlecenieID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

App/Views/Zlecenia/Edit.cshtml
@model App.Models.Zlecenia





@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h2>Zlecenia</h2>
        <h4>Edycja</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ZlecenieID)

        <div class="form-group">
            @Html.LabelFor(model => model.Firma, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Firma, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Firma, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Termin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Termin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Termin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Zapisz" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Wróć do listy", "Index")
</div>

App/Views/Zlecenia/Index.cshtml
@model PagedList.IPagedList<App.Models.Zlecenia>

@{
    ViewBag.Title = "Index";
}
@using PagedList.Mvc;
@using PagedList;

<h2>Zlecenia</h2>
@using (Html.BeginForm("Index", "Zlecenia", FormMethod.Get))
{
    <p>
        @Html.TextBox("search", ViewBag.filter as string)
        <input type="submit" value="Szukaj" />
    </p>
}
<p>
    @Html.ActionLink("Dodaj", "Create")
</p>
<table class="table table-hover">
    <tr>
        <th>

            @Html.ActionLink("Firma", "Index", new { sortowanie = ViewBag.Firma, page = ViewBag.Strona, filter = ViewBag.filter}, new { style = "color: black;" })
        </th>
        <th>

            @Html.ActionLink("Termin", "Index", new { sortowanie = ViewBag.Termin, page = ViewBag.Strona, filter = ViewBag.filter }, new { style = "color: black;" })
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Firma)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Termin)
            </td>
            <td>
                @Html.ActionLink("Edytuj", "Edit", new { id = item.ZlecenieID }, new { @class = "Edycja" })
                @Html.ActionLink("Usuń", "Delete", new { id = item.ZlecenieID }, new { @class = "Delete" })
            </td>
        </tr>
    }

</table>





Strona @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortowanie = ViewBag.SortBy, filter = ViewBag.filter }))