App/Models/Zaginanie.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zaginanie
    {
        public int ProduktID { get; set; }
        public Nullable<int> IloscWykonana { get; set; }
        public Nullable<int> CzasZaginania { get; set; }
        public string Pogieto { get; set; }
    
        public virtual Produkty Produkty { get; set; }
    }
}

App/Controllers/ZaginanieController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using App.Models;
using PagedList;

namespace App.Controllers
{
    [Authorize]
    public class ZaginanieController : Controller
    {
        private EntityDBEntities db = new EntityDBEntities();

        // GET: Zaginanie
        public ActionResult Index(string sortowanie, string search, string filter, int? page)
        {
            int pageNumber = (page ?? 1);

            ViewBag.Wyszukiwanie = search;
            ViewBag.Strona = page;
            ViewBag.SortBy = sortowanie;
            ViewBag.Produkt = sortowanie == "ProduktDSC" ? "ProduktASC" : "ProduktDSC";
            ViewBag.Termin = sortowanie == null ? "TerminDSC" : "";
            ViewBag.IloscZamowiona = sortowanie == "IloscZamowionaDSC" ? "IloscZamowionaASC" : "IloscZamowionaDSC";

            if (search != null)
            {
                page = 1;
            }
            else
            {
                search = filter;
            }
            ViewBag.filter = search;

            var query = from p in db.Produkty
                        join z in db.Zaginanie on p.ProduktID equals z.ProduktID
                        join w in db.Wypalanie on p.ProduktID equals w.ProduktID
                        where w.Wypalono == "tak" && z.Pogieto == "nie"
                        select z;
            if (!String.IsNullOrEmpty(search))
            {
                query = from za in db.Zaginanie
                        join p in db.Produkty on za.ProduktID equals p.ProduktID
                        join z in db.Zlecenia on p.ZlecenieID equals z.ZlecenieID
                        join w in db.Wypalanie on p.ProduktID equals w.ProduktID
                        where p.Produkt.Contains(search) && za.Pogieto == "nie" && w.Wypalono == "tak" ||
                        p.Uwagi.Contains(search) && za.Pogieto == "nie" && w.Wypalono == "tak" ||
                        p.IloscZamowiona.ToString().Contains(search) && za.Pogieto == "nie" && w.Wypalono == "tak" ||
                        z.Termin.ToString().Contains(search) && za.Pogieto == "nie" && w.Wypalono == "tak"
                        select za;
            }

            switch (sortowanie)
            {
                case "ProduktDSC":
                    query = query.OrderByDescending(s => s.Produkty.Produkt);
                    break;
                case "ProduktASC":
                    query = query.OrderBy(s => s.Produkty.Produkt);
                    break;
                case "TerminDSC":
                    query = query.OrderByDescending(s => s.Produkty.Zlecenia.Termin);
                    break;
                default:
                    query = query.OrderBy(s => s.Produkty.Zlecenia.Termin);
                    break;
                case "IloscZamowionaDSC":
                    query = query.OrderByDescending(s => s.Produkty.IloscZamowiona);
                    break;
                case "IloscZamowionaASC":
                    query = query.OrderBy(s => s.Produkty.IloscZamowiona);
                    break;

            }



            return View(query.ToPagedList(pageNumber, 6));
        }

        

        // GET: Zaginanie/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Zaginanie zaginanie = db.Zaginanie.Find(id);
            if (zaginanie == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProduktID = new SelectList(db.Produkty, "ProduktID", "Produkt", zaginanie.ProduktID);
            return View(zaginanie);
        }

        // POST: Zaginanie/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProduktID,IloscWykonana,CzasZaginania,Pogieto")] Zaginanie zaginanie)
        {
            if (ModelState.IsValid)
            {
                db.Entry(zaginanie).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ProduktID = new SelectList(db.Produkty, "ProduktID", "Produkt", zaginanie.ProduktID);
            return View(zaginanie);
        }

        

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

App/Views/Zaginanie/Edit.cshtml
@model App.Models.Zaginanie


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h2>Zaginanie</h2>
    <h4>Edycja</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ProduktID)

    <div class="form-group">
        @Html.LabelFor(model => model.IloscWykonana, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.IloscWykonana, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.IloscWykonana, "", new { @class = "text-danger" })

        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CzasZaginania, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CzasZaginania, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CzasZaginania, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Pogieto, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            nie:
            @Html.RadioButtonFor(model => model.Pogieto, "nie")
            tak:
            @Html.RadioButtonFor(model => model.Pogieto, "tak")
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Zapisz" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Wróć do listy", "Index")
</div>

App/Views/Zaginanie/Index.cshtml
@model PagedList.IPagedList<App.Models.Zaginanie>
@using PagedList.Mvc;
<h2>Zaginanie</h2>
@using (Html.BeginForm("Index", "Zaginanie", FormMethod.Get))
{
    <p>
        @Html.TextBox("search", ViewBag.filter as string)
        <input type="submit" value="Szukaj" />
    </p>
}
<br /><br />
    <table class="table table-hover">
        <tr>
            <th>
                @Html.ActionLink("Produkt", "Index", new { sortowanie = ViewBag.Produkt, page = ViewBag.Strona, filter = ViewBag.filter }, new { style = "color: black;" })
            </th>
            <th>
                @Html.ActionLink("Termin", "Index", new { sortowanie = ViewBag.Termin, page = ViewBag.Strona, filter = ViewBag.filter }, new { style = "color: black;" })
            </th>
            <th>
                @Html.ActionLink("Ilość Zamówiona", "Index", new { sortowanie = ViewBag.IloscZamowiona, page = ViewBag.Strona, filter = ViewBag.filter }, new { style = "color: black;" })
            </th>
            <th style="color: black">
                IloscWykonana
            </th>
            <th style="color: black">
                CzasZaginania
            </th>
            <th style="color: black">
                Pogieto
            </th>
            <th style="color: black">
                Uwagi
            </th>
            <th></th>
        </tr>


        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Produkty.Produkt)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Produkty.Zlecenia.Termin)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Produkty.IloscZamowiona)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IloscWykonana)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CzasZaginania)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Pogieto)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Produkty.Uwagi)
                </td>
                <td>
                    @Html.ActionLink("Edytuj", "Edit", new { id = item.ProduktID }, new { @class = "Edycja" })
                </td>
            </tr>
        }

    </table>
    Strona @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount

    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortowanie = ViewBag.SortBy, filter = ViewBag.filter }))