App/Models/Produkty.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produkty
    {
        public int ProduktID { get; set; }
        public Nullable<int> ZlecenieID { get; set; }
        public string Produkt { get; set; }
        public Nullable<int> IloscZamowiona { get; set; }
        public string Uwagi { get; set; }
    
        public virtual Magazyn Magazyn { get; set; }
        public virtual Zlecenia Zlecenia { get; set; }
        public virtual Spawanie Spawanie { get; set; }
        public virtual Wypalanie Wypalanie { get; set; }
        public virtual Zaginanie Zaginanie { get; set; }
    }
}

App/Controllers/ProduktyController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using App.Models;
using PagedList;

namespace App.Controllers
{
    [Authorize]
    public class ProduktyController : Controller
    {
        private EntityDBEntities db = new EntityDBEntities();

        // GET: Produkty
        public ActionResult Index(string sortowanie, string search, string filter, int? page)
        {

            ViewBag.Wyszukiwanie = search;
            ViewBag.Strona = page;
            ViewBag.SortBy = sortowanie;
            ViewBag.Produkt = sortowanie == null ? "ProduktDSC" : "";
            ViewBag.IloscZamowiona = sortowanie == "IloscZamowionaDSC" ? "IloscZamowionaASC" : "IloscZamowionaDSC";
            ViewBag.Firma = sortowanie == "FirmaDSC" ? "FirmaASC" : "FirmaDSC";
            ViewBag.Uwagi = sortowanie == "UwagiDSC" ? "UwagiASC" : "UwagiDSC";

            if (search != null)
            {
                page = 1;
            }
            else
            {
                search = filter;
            }
            ViewBag.filter = search;

            int pageNumber = (page ?? 1);
            var query = from p in db.Produkty
                        select p;

            if (!String.IsNullOrEmpty(search))
            {
                query = from p in db.Produkty
                        join z in db.Zlecenia on p.ZlecenieID equals z.ZlecenieID
                        where p.Produkt.Contains(search) || p.Uwagi.Contains(search) ||
                        p.IloscZamowiona.ToString().Contains(search) || z.Firma.Contains(search)
                        select p;
            }

            switch (sortowanie)
            {
                case "ProduktDSC":
                    query = query.OrderByDescending(s => s.Produkt);
                    break;
                case "IloscZamowionaDSC":
                    query = query.OrderByDescending(s => s.IloscZamowiona);
                    break;
                case "IloscZamowionaASC":
                    query = query.OrderBy(s => s.IloscZamowiona);
                    break;
                case "FirmaDSC":
                    query = query.OrderByDescending(s => s.Zlecenia.Firma);
                    break;
                case "FirmaASC":
                    query = query.OrderBy(s => s.Zlecenia.Firma);
                    break;
                case "UwagiDSC":
                    query = query.OrderByDescending(s => s.Uwagi);
                    break;
                case "UwagiASC":
                    query = query.OrderBy(s => s.Uwagi);
                    break;
                default:
                    query = query.OrderBy(s => s.Produkt);
                    break;
            }



            return View(query.ToPagedList(pageNumber, 6));
        }


        // GET: Produkty/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.ZlecenieID = new SelectList(db.Zlecenia, "ZlecenieID", "Firma");
            return View();
        }

        // POST: Produkty/Create
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProduktID,ZlecenieID,Produkt,IloscZamowiona,Uwagi")] Produkty produkty)
        {
            if (ModelState.IsValid)
            {
                Wypalanie wypalanie = new Wypalanie();
                Zaginanie zaginanie = new Zaginanie();
                Spawanie spawanie = new Spawanie();
                Magazyn magazyn = new Magazyn();

                wypalanie.Wypalono = "nie";
                zaginanie.Pogieto = "nie";
                spawanie.Pospawano = "nie";
                magazyn.Spakowano = "nie";
                magazyn.Wyslano = "nie";

                produkty.ProduktID = wypalanie.ProduktID;
                produkty.ProduktID = zaginanie.ProduktID;
                produkty.ProduktID = spawanie.ProduktID;
                produkty.ProduktID = magazyn.ProduktID;

                db.Magazyn.Add(magazyn);
                db.Spawanie.Add(spawanie);
                db.Zaginanie.Add(zaginanie);
                db.Wypalanie.Add(wypalanie);
                db.Produkty.Add(produkty);

                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ZlecenieID = new SelectList(db.Zlecenia, "ZlecenieID", "Firma", produkty.ZlecenieID);
            return View(produkty);
        }

        // GET: Produkty/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produkty produkty = db.Produkty.Find(id);
            if (produkty == null)
            {
                return HttpNotFound();
            }
            ViewBag.ZlecenieID = new SelectList(db.Zlecenia, "ZlecenieID", "Firma", produkty.ZlecenieID);
            return View(produkty);
        }

        // POST: Produkty/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProduktID,ZlecenieID,Produkt,IloscZamowiona,Uwagi")] Produkty produkty)
        {
            if (ModelState.IsValid)
            {
                db.Entry(produkty).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ZlecenieID = new SelectList(db.Zlecenia, "ZlecenieID", "Firma", produkty.ZlecenieID);
            
            return View(produkty);
        }

        // GET: Produkty/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produkty produkty = db.Produkty.Find(id);
            if (produkty == null)
            {
                return HttpNotFound();
            }
            return View(produkty);
        }

        // POST: Produkty/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Magazyn magazyn = db.Magazyn.Find(id);
            Spawanie spawanie = db.Spawanie.Find(id);
            Zaginanie zaginanie = db.Zaginanie.Find(id);
            Wypalanie wypalanie = db.Wypalanie.Find(id);
            Produkty produkty = db.Produkty.Find(id);

            db.Magazyn.Remove(magazyn);
            db.Spawanie.Remove(spawanie);
            db.Zaginanie.Remove(zaginanie);
            db.Wypalanie.Remove(wypalanie);
            db.Produkty.Remove(produkty);
            
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult Postep(string sortowanie,string search, string filter, int? page)
        {

            ViewBag.Strona = page;
            ViewBag.SortBy = sortowanie;
            ViewBag.Wyszukiwanie = search;

            

            if (search != null)
            {
                page = 1;
            }
            else
            {
                search = filter;
            }
            ViewBag.filter = search;

            var query = from p in db.Produkty
                        select p;

            if (!String.IsNullOrEmpty(search))
            {
                query = from z in db.Zlecenia
                        join p in db.Produkty on z.ZlecenieID equals p.ZlecenieID
                        join w in db.Wypalanie on p.ProduktID equals w.ProduktID
                        join za in db.Zaginanie on p.ProduktID equals za.ProduktID
                        join s in db.Spawanie on p.ProduktID equals s.ProduktID
                        join m in db.Magazyn on p.ProduktID equals m.ProduktID
                        where p.Produkt.Contains(search) || z.Firma.Contains(search) ||
                        z.Termin.ToString().Contains(search) || w.Wypalono.Contains(search) ||
                        za.Pogieto.Contains(search) || s.Pospawano.Contains(search) ||
                        m.Spakowano.Contains(search) || m.Wyslano.Contains(search) ||
                        p.Uwagi.Contains(search)
                        select p;

            }
            ViewBag.Produkt = sortowanie == "ProduktDSC" ? "ProduktASC" : "ProduktDSC";
            ViewBag.Firma = sortowanie == "FirmaDSC" ? "FirmaASC" : "FirmaDSC";
            ViewBag.Termin = sortowanie == null ? "TerminDSC" : "";
            ViewBag.Wypalono = sortowanie == "WypalonoDSC" ? "WypalonoASC" : "WypalonoDSC";
            ViewBag.Pogieto = sortowanie == "PogietoDSC" ? "PogietoASC" : "PogietoDSC";
            ViewBag.Pospawano = sortowanie == "PospawanoDSC" ? "PospawanoASC" : "PospawanoDSC";
            ViewBag.Spakowano = sortowanie == "SpakowanoDSC" ? "SpakowanoASC" : "SpakowanoDSC";
            ViewBag.Wyslano = sortowanie == "WyslanoDSC" ? "WyslanoASC" : "WyslanoDSC";
            ViewBag.Uwagi = sortowanie == "UwagiDSC" ? "UwagiASC" : "UwagiDSC";

App/Views/Produkty/Create.cshtml
@model App.Models.Produkty



<h2>Nowy produkt</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Produkty</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ZlecenieID, "ZlecenieID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ZlecenieID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ZlecenieID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Produkt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Produkt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Produkt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IloscZamowiona, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IloscZamowiona, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IloscZamowiona, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Uwagi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Uwagi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Uwagi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Utwórz" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Wróć do listy", "Index")
</div>

App/Views/Produkty/Delete.cshtml
@model App.Models.Produkty

@{
    ViewBag.Title = "Delete";
}



<h3>Czy na pewno chcesz usunąć ten produkt?</h3>
<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Produkt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Produkt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IloscZamowiona)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IloscZamowiona)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Uwagi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Uwagi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zlecenia.Firma)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zlecenia.Firma)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Usuń" class="btn btn-default" /> |
            @Html.ActionLink("Wróć do listy", "Index")
        </div>
    }
</div>

App/Views/Produkty/Details.cshtml
@model App.Models.Produkty

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Produkty</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Produkt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Produkt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IloscZamowiona)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IloscZamowiona)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Uwagi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Uwagi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zlecenia.Firma)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zlecenia.Firma)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ProduktID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

App/Views/Produkty/Edit.cshtml
@model App.Models.Produkty



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h2>Produkty</h2>
        <h4>Edycja</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProduktID)

        <div class="form-group">
            @Html.LabelFor(model => model.ZlecenieID, "ZlecenieID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ZlecenieID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ZlecenieID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Produkt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Produkt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Produkt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IloscZamowiona, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IloscZamowiona, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IloscZamowiona, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Uwagi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Uwagi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Uwagi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Zapisz" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Wróć do listy", "Index")
</div>

App/Views/Produkty/Index.cshtml
@model PagedList.IPagedList<App.Models.Produkty>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Index";
}

<h2>Produkty</h2>
@using (Html.BeginForm("Index", "Produkty", FormMethod.Get))
{
    <p>
        @Html.TextBox("search", ViewBag.filter as string)
        <input type="submit" value="Szukaj" />
    </p>
}

<p>
    @Html.ActionLink("Dodaj", "Create")
</p>

<table class="table table-hover">
    <tr>
        <th>
            @Html.ActionLink("Produkt", "Index", new { sortowanie = ViewBag.Produkt, page = ViewBag.Strona, filter = ViewBag.filter }, new { style = "color: black;" })
        </th>
        <th>
            @Html.ActionLink("Ilość Zamówiona", "Index", new { sortowanie = ViewBag.IloscZamowiona, page = ViewBag.Strona, filter = ViewBag.filter }, new { style = "color: black;" })
        </th>
        <th>
            @Html.ActionLink("Uwagi", "Index", new { sortowanie = ViewBag.Uwagi, page = ViewBag.Strona, filter = ViewBag.filter }, new { style = "color: black;" })
        </th>
        <th>
            @Html.ActionLink("Firma", "Index", new { sortowanie = ViewBag.Firma, page = ViewBag.Strona, filter = ViewBag.filter }, new { style = "color: black;" })
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Produkt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IloscZamowiona)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Uwagi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Zlecenia.Firma)
            </td>
            <td>
                @Html.ActionLink("Edytuj", "Edit", new { id = item.ProduktID }, new { @class = "Edycja" })
                @Html.ActionLink("Usuń", "Delete", new { id = item.ProduktID }, new { @class = "Delete" })
            </td>
        </tr>
    }

</table>

Strona @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortowanie = ViewBag.SortBy, filter = ViewBag.filter }))

App/Views/Produkty/Postep.cshtml
@model PagedList.IPagedList<App.Models.Produkty>
@using PagedList.Mvc;


<h2>Postęp</h2>
@using (Html.BeginForm("Postep", "Produkty", FormMethod.Get))
{
    <p>
        @Html.TextBox("search", ViewBag.filter as string)
        <input type="submit" value="Szukaj" />
    </p>
}
<br /><br />

<table class="table table-hover">
    <tr>
        <td>@Html.ActionLink("Produkt", "Postep", new { sortowanie = ViewBag.Produkt, page = ViewBag.Strona, filter = ViewBag.filter }, new { style = "color: black;" })</td>
        <td>@Html.ActionLink("Firma", "Postep", new { sortowanie = ViewBag.Firma, page = ViewBag.Strona, filter = ViewBag.filter }, new { style = "color: black;" })</td>
        <td>@Html.ActionLink("Termin", "Postep", new { sortowanie = ViewBag.Termin, page = ViewBag.Strona, filter = ViewBag.filter }, new { style = "color: black;" })</td>
        <td>@Html.ActionLink("Wypalono", "Postep", new { sortowanie = ViewBag.Wypalono, page = ViewBag.Strona, filter = ViewBag.filter }, new { style = "color: black;" })</td>
        <td>@Html.ActionLink("Pogięto", "Postep", new { sortowanie = ViewBag.Pogieto, page = ViewBag.Strona, filter = ViewBag.filter }, new { style = "color: black;" })</td>
        <td>@Html.ActionLink("Pospawano", "Postep", new { sortowanie = ViewBag.Pospawano, page = ViewBag.Strona, filter = ViewBag.filter }, new { style = "color: black;" })</td>
        <td>@Html.ActionLink("Spakowano", "Postep", new { sortowanie = ViewBag.Spakowano, page = ViewBag.Strona, filter = ViewBag.filter }, new { style = "color: black;" })</td>
        <td>@Html.ActionLink("Wysłano", "Postep", new { sortowanie = ViewBag.Wyslano, page = ViewBag.Strona, filter = ViewBag.filter }, new { style = "color: black;" })</td>
        <td>@Html.ActionLink("Uwagi", "Postep", new { sortowanie = ViewBag.Uwagi, page = ViewBag.Strona, filter = ViewBag.filter }, new { style = "color: black;" })</td>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@Html.DisplayFor(modelItem => item.Produkt)</td>
            <td>@Html.DisplayFor(modelItem => item.Zlecenia.Firma)</td>
            <td>@Html.DisplayFor(modelItem => item.Zlecenia.Termin)</td>
            <td>@Html.DisplayFor(modelItem => item.Wypalanie.Wypalono)</td>
            <td>@Html.DisplayFor(modelItem => item.Zaginanie.Pogieto)</td>
            <td>@Html.DisplayFor(modelItem => item.Spawanie.Pospawano)</td>
            <td>@Html.DisplayFor(modelItem => item.Magazyn.Spakowano)</td>
            <td>@Html.DisplayFor(modelItem => item.Magazyn.Wyslano)</td>
            <td>@Html.DisplayFor(modelItem => item.Uwagi)</td>
        </tr>
    }
</table>

Strona @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Postep", new { page, sortowanie = ViewBag.SortBy, filter = ViewBag.filter }))