App/Models/Wypalanie.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wypalanie
    {
        public int ProduktID { get; set; }
        public Nullable<int> IloscWykonana { get; set; }
        public Nullable<int> CzasWypalania { get; set; }
        public string Wypalono { get; set; }
    
        public virtual Produkty Produkty { get; set; }
    }
}

App/Controllers/WypalanieController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using App.Models;
using PagedList;


namespace App.Controllers
{
    [Authorize]
    public class WypalanieController : Controller
    {
        private EntityDBEntities db = new EntityDBEntities();

        // GET: Wypalanie
        public ActionResult Index(string sortowanie, string search, string filter, int? page)
        {
            int pageNumber = (page ?? 1);

            ViewBag.Wyszukiwanie = search;
            ViewBag.Strona = page;
            ViewBag.SortBy = sortowanie;
            ViewBag.Produkt = sortowanie == "ProduktDSC" ? "ProduktASC" : "ProduktDSC";
            ViewBag.Termin = sortowanie == null ? "TerminDSC" : "";
            ViewBag.IloscZamowiona = sortowanie == "IloscZamowionaDSC" ? "IloscZamowionaASC" : "IloscZamowionaDSC";

            if (search != null)
            {
                page = 1;
            }
            else
            {
                search = filter;
            }
            ViewBag.filter = search;
            
            var query = from p in db.Produkty
                        join w in db.Wypalanie on p.ProduktID equals w.ProduktID
                        where w.Wypalono == "nie"
                        select w;

            if (!String.IsNullOrEmpty(search))
            {
                query = from w in db.Wypalanie
                        join p in db.Produkty on w.ProduktID equals p.ProduktID
                        join z in db.Zlecenia on p.ZlecenieID equals z.ZlecenieID
                        where p.Produkt.Contains(search) && w.Wypalono == "nie" ||
                        p.Uwagi.Contains(search) && w.Wypalono == "nie" ||
                        p.IloscZamowiona.ToString().Contains(search) && w.Wypalono == "nie" ||
                        z.Termin.ToString().Contains(search) && w.Wypalono == "nie"
                        select w;
            }

            switch (sortowanie)
            {
                case "ProduktDSC":
                    query = query.OrderByDescending(s => s.Produkty.Produkt);
                    break;
                case "ProduktASC":
                    query = query.OrderBy(s => s.Produkty.Produkt);
                    break;
                case "TerminDSC":
                    query = query.OrderByDescending(s => s.Produkty.Zlecenia.Termin);
                    break;
                case "IloscZamowionaDSC":
                    query = query.OrderByDescending(s => s.Produkty.IloscZamowiona);
                    break;
                case "IloscZamowionaASC":
                    query = query.OrderBy(s => s.Produkty.IloscZamowiona);
                    break;
                default:
                    query = query.OrderBy(s => s.Produkty.Zlecenia.Termin);
                    break;

            }



            return View(query.ToPagedList(pageNumber, 6));
        }

        
        // GET: Wypalanie/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Wypalanie wypalanie = db.Wypalanie.Find(id);
            if (wypalanie == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProduktID = new SelectList(db.Produkty, "ProduktID", "Produkt", wypalanie.ProduktID);
            
            return View(wypalanie);
        }

        // POST: Wypalanie/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProduktID,IloscWykonana,CzasWypalania,Wypalono")] Wypalanie wypalanie)
        {
            if (ModelState.IsValid)
            {
                db.Entry(wypalanie).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ProduktID = new SelectList(db.Produkty, "ProduktID", "Produkt", wypalanie.ProduktID);
            return View(wypalanie);
        }

        
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

App/Views/Wypalanie/Edit.cshtml
@model App.Models.Wypalanie


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h2>Wypalanie</h2>
    <h4>Edycja</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ProduktID)

    <div class="form-group">
        @Html.LabelFor(model => model.IloscWykonana, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.IloscWykonana, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.IloscWykonana, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CzasWypalania, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CzasWypalania, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CzasWypalania, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Wypalono, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            nie:
            @Html.RadioButtonFor(model => model.Wypalono, "nie")
            tak:
            @Html.RadioButtonFor(model => model.Wypalono, "tak")
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Zapisz" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Wróć do listy", "Index")
</div>

App/Views/Wypalanie/Index.cshtml
@model PagedList.IPagedList<App.Models.Wypalanie>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Index";
}
<h2>Wypalanie</h2>
@using (Html.BeginForm("Index", "Wypalanie", FormMethod.Get))
{
    <p>
        @Html.TextBox("search", ViewBag.filter as string)
        <input type="submit" value="Szukaj" />
    </p>
}
<br /><br />


<table class="table table-hover">
    <tr>
        <th>
            @Html.ActionLink("Produkt", "Index", new { sortowanie = ViewBag.Produkt, page = ViewBag.Strona, filter = ViewBag.filter }, new { style = "color: black;" })
        </th>
        <th>
            @Html.ActionLink("Termin", "Index", new { sortowanie = ViewBag.Termin, page = ViewBag.Strona, filter = ViewBag.filter }, new { style = "color: black;" })
        </th>
        <th>
            @Html.ActionLink("Ilość Zamówiona", "Index", new { sortowanie = ViewBag.IloscZamowiona, page = ViewBag.Strona, filter = ViewBag.filter }, new { style = "color: black;" })
        </th>
        <th style="color: black">
            Ilość Wykonana
        </th>
        <th style="color: black">
            Czas Wypalania
        </th>
        <th style="color: black">
            Wypalono
        </th>
        <th style="color: black">
            Uwagi
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Produkty.Produkt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Produkty.Zlecenia.Termin)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Produkty.IloscZamowiona)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IloscWykonana)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CzasWypalania)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Wypalono)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Produkty.Uwagi)
            </td>
            <td>
                @Html.ActionLink("Edytuj", "Edit", new { id = item.ProduktID }, new { @class = "Edycja" })

            </td>
        </tr>
    }

</table>
Strona @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortowanie = ViewBag.SortBy, filter = ViewBag.filter }))